global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
- job_name: app1
  scheme: https
  metrics_path: /actuator/prometheus
  static_configs:
    - targets:
      - "app1.cfapps.io"
      labels:
        application: app1
